# 这个action用于同步development到武汉development

name: sync-development

on:
  push:
    branches: 
      - development

jobs:

  sync:
    name: sync
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: sync development to wuhan
    - run: git checkout wh_dev
    - run: git reset --hard origin/development
    - run: git push -f origin wh_dev.
           
